### ISSUE TITLE
可以提供一个方法来判断"是否已经init过"吗?

### ISSUE THREAD

**Issue by lsby** [hungtcs/baidu-fanyi-api#1]
## 为什么

每次都init很慢

## 预期

提供一个函数或状态,例如 api.isInit 来判断是否已init过, 我就可以通过判断这个状态来确定每次调用是否需要init.

## 现状

并没有这样的状态, 也许可以通过 api.baiduID 或 api.token 判断?

**Comment by hungtcs** [comment]
@lsby 初始化方法仅调用一次就可以了，不需要每次调用，一般不会出现需要判断是否初始化的需求，你现在可以更新`baidu-fanyi-api`到`0.0.3`，然后使用`api.inited`标志判断是否执行过`init()`方法

**Comment by hungtcs** [comment]
Fixed in https://github.com/hungtcs/baidu-fanyi-api/commit/f3b49897cb661473b886cf331fe8baa7ac2c3f07
