### ISSUE TITLE
该项目node 版本多少？用8报了个正则的错

### ISSUE THREAD

**Issue by mjpcasey** [hungtcs/baidu-fanyi-api#2]
版本8.15.0
这个是正确的：
console.log(this.html.match(/window.gtk\s*=\s*'(.*?)'/)) 
下面是错的
     console.log(this.html.match(/window.gtk\s*=\s*'(?<gtk>.+)'/))
     this.gtk = this.html.match(/window.gtk\s*=\s*'(?<gtk>.+)'/).groups.gtk;
     this.token = this.html.match(/token:\s*'(?<token>.+)',/).groups.token;

**Comment by hungtcs** [comment]
根据node.green，需要10.3.0才可以支持`named-capture-groups`.

- https://node.green/#ES2018-features--RegExp-named-capture-groups
